### ISSUE TITLE
Can't connect, Hoodie skips password prompt

### ISSUE THREAD

**Issue by username1290** [passcod/docker-prototypo#1]
Hi, tried to run it but Hoodie doesn't stop at the password prompt

part of the terminal output:

Initializing...
Using remote CouchDB: http://localhost:5984
[info] [<0.104.0>] 127.0.0.1 - - GET / 200
Waiting for CouchDB [-*----] SUCCESS 
[info] [<0.105.0>] 127.0.0.1 - - HEAD /_users/_all_docs 200
[info] [<0.106.0>] 127.0.0.1 - - PUT /_config/admins/_hoodie 200
**prompt: Please set an admin password :**  Running "serve" task

Running "clean:server" (clean) task

Running "concurrent:server" (concurrent) task
...

it just skips this part, and can't connect to the Hoodie admin (6002).

**Comment by passcod** [comment]
Hi! This is not maintained, and indeed I haven't used this in years. If you get it working I'd accept a PR, but I'm not going to work on that, sorry :)
